# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export TERM="xterm-256color"

export ZSH=$HOME/.oh-my-zsh


# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="superjarin"
ZSH_THEME="robbyrussell"
# ZSH_THEME="agnoster"
# # Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(vi-mode docker-compose docker-machine git bundler rails zsh-autosuggestions zsh-syntax-highlighting yarn npm docker colored-man-pages)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
  export GIT_EDITOR='nvim'
else
  export EDITOR='nvim'
  export GIT_EDITOR='nvim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#

# misc
alias tag-gen="ctags -R --tag-relative -f .git/tags"

# Emacs *shrug*
export PATH="$PATH:$HOME/.emacs.d/bin"

# go
export GOPATH=$HOME/go
export GOROOT=/usr/lib/go
export PATH=$PATH:$GOPATH
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

# various bin locations
export PATH=$PATH:/snap/bin
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/bin:$PATH

# Yarn
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# for use with Sops
GPG_TTY=$(tty)
export GPG_TTY
export GCM_CREDENTIAL_STORE="gpg"

DOT_ZSH="$HOME/.zsh"

# source aliases
source "$DOT_ZSH/aliases"

# add functions
for function in "$DOT_ZSH"/functions/*; do
  source $function
done

if [[ "$OSTYPE" =~ "linux" ]]; then
  source $HOME/.asdf/completions/asdf.bash
  source $HOME/.asdf/asdf.sh
elif [[ "$OSTYPE" =~ "darwin" ]]; then
  export PATH="$(brew --prefix)/bin:$PATH"
  export PATH="$HOME/nvim-osx64/bin:$PATH"
  export JAVA_HOME="$(brew --prefix java)"
  export PATH="$JAVA_HOME/bin:$PATH"

  # # Workaround for mimemagic
  export FREEDESKTOP_MIME_TYPES_PATH="$(brew --prefix)/share/mime/packages/freedesktop.org.xml"

  source "$(brew --prefix asdf)/asdf.sh"
  source "$(brew --prefix asdf)/etc/bash_completion.d/asdf.bash"
  alias ctags='`brew --prefix`/bin/ctags'
  alias ls='ls -G'

  export PNPM_HOME="$HOME/Library/pnpm"
  export PATH="$PNPM_HOME:$PATH"

  test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh" || true
fi

node_version="$(node -v)"
export NODE_VERSION="${node_version:1}"
export NODE_PATH="$HOME/.asdf/installs/nodejs/${$(node -v)}/.npm/lib"
export CARGO_PATH="$HOME/.cargo/bin"
export PATH="$CARGO_PATH:$PATH"

autoload -Uz compinit && compinit -i
autoload -U zmv
eval "$(direnv hook zsh)"


# pnpm
export PNPM_HOME="$HOME/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end
export HOMEBREW_PREFIX="/opt/homebrew"

if [[ -f "$HOME/.cf2_secrets" ]]; then
  source "$HOME/.cf2_secrets"
fi
