set encoding=utf-8
" Plugins{{{
" Will install plugin manager if not detected
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin("~/.vim/plugged")
  "Colorschemes
  Plug 'flazz/vim-colorschemes'
  Plug 'zeis/vim-kolor'
  Plug 'paramagicdev/vim-medic-chalk'

  "Tpope plugins
  Plug 'tpope/vim-fugitive'
  Plug 'tpope/vim-commentary'
  Plug 'tpope/vim-surround'
  Plug 'tpope/vim-ragtag'
  Plug 'tpope/vim-dispatch'

  "Javascript / React
  Plug 'yuezk/vim-js'
  Plug 'elzr/vim-json'
  Plug 'maxmellon/vim-jsx-pretty'
  Plug 'jxnblk/vim-mdx-js'

  " Typescript
  Plug 'leafgarland/typescript-vim'
  Plug 'peitalin/vim-jsx-typescript'

  "ruby / rails
  Plug 'vim-ruby/vim-ruby'
  Plug 'tpope/vim-rails'
  Plug 'tpope/vim-bundler'

  " Elixir
  Plug 'elixir-editors/vim-elixir'

  " Tests
  Plug 'janko/vim-test'

  "html / css
  Plug 'mattn/emmet-vim'
  Plug 'ap/vim-css-color'

  " Snippets
  Plug 'SirVer/ultisnips'

  "Misc
  Plug 'junegunn/rainbow_parentheses.vim'

  "Linting
  Plug 'dense-analysis/ale'

  " fuzzy finding
  Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }

  " File explorer
  Plug 'preservim/nerdtree'

  "LSP
  if has("nvim-0.5")
    Plug 'neovim/nvim-lspconfig'

    " Completion
    Plug 'nvim-lua/completion-nvim'
    Plug 'steelsojka/completion-buffers'
  endif
call plug#end()
"}}}
" Defaults {{{
" Path variables, prepend current directory
set path^=.,,

" Autosave
set autowrite

"indentations
set smartindent
set autoindent
set preserveindent
set copyindent

"tabs
set expandtab       "expand tabs into spaces
set tabstop=2 " when indenting with '>', use 4 spaces width
set shiftwidth=2 " On pressing tab, insert 4 spaces
set shiftround

"Make it obvious where 80 characters is
set colorcolumn=81

"Left hand column numbers
set number
set relativenumber

"Display extra whitespace
set list listchars=tab:»·,trail:·,nbsp:·

"show matching brackets
set showmatch

"show cursor position at all times
set ruler

"don't highlight the previous search term
set nohls

"incremental searching
set incsearch

" incremental commands
if exists('+inccommand')
  set inccommand=nosplit
endif

"turn on visual word wrapping
set wrap

"only break lines on 'breakat' characters
set linebreak

" Folds
set foldmethod=syntax

"Syntax highlighting
syntax on

"Enable filetypes, indentation and plugins
filetype plugin indent on

"Say no to file backups
set nobackup
set nowritebackup
set noswapfile

"fixes backspace in vim
set backspace=indent,eol,start

"fix backspace on some consoles
set bs=2

"Tabbing menu
set wildmenu
set wildmode=full
set wildignorecase

set wildignore+=*/node_modules/*
set wildignore+=*/coverage/*
set wildignore+=*/public/*
set wildignore+=*/.git/*,*/tmp/*,*/.tmp/*
set wildignore+=*/.bundle/*,*/vendor/*,*/log/*

"show command line
set showcmd

"keep small history
set history=50

"Keep buffers alive in background
set hidden

"Fixes files at the end of macros, better performance
set lazyredraw

"Stupid clipboard crap, configure this accordingly
set clipboard+=unnamedplus

"Provide a line of what column youre in
set cursorcolumn

"Adds a horizontal highlight to current line
set cursorline

" Global substitutions by default
set gdefault

"Fixing splits to be more natural
set splitbelow
set splitright

" Always use vertical diffs
set diffopt+=vertical

" 'matchit.vim' is built-in so let's enable it!
" " Hit '%' on 'if' to jump to 'else'.
runtime macros/matchit.vim

" Tags searching
set tags+=./.git/tags
set tags+=./tags
"}}}
" Autocmds {{{
" For Kolor colorscheme
augroup MyColors
  autocmd!
  autocmd ColorScheme kolor call myhighlights#KolorHighlights()
  autocmd ColorScheme medic_chalk call myhighlights#MedicChalkHighlights()
augroup END


" Strip whitespace
autocmd BufWritePre * %s/\s\+$//e

" Proper file completion
augroup FilenameCompletion
  autocmd!
  autocmd InsertEnter * execute 'cd %:h'
  autocmd InsertLeave * execute 'cd -'
augroup END

" Return cursor to original position
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
  \| exe "normal g'\"" | endif
endif
"}}}
"Colorscheme / appearance{{{
set background=dark
colorscheme kolor
" set termguicolors


"Status line
set laststatus=2
set statusline=
set statusline+=\ %<%F\ %m\ %r\ %h\ %=%=%=%y\ [%c]%=
"}}}
" Sensible stuff{{{

"<Leader> is now <space>
let mapleader = " "

" Jump down sensibly
nnoremap j gj
nnoremap k gk

set helpheight=20
"}}}
" Movement{{{
" Using splits
map <Leader>sp :split<space>
nnoremap <Leader>vs :vsplit<space>

"Buffer switching

" Prev buffer
nnoremap <Leader><Leader> <C-^>
nnoremap [b :bprev<CR>
nnoremap ]b :bnext<CR>
nnoremap <C-b> :bdelete<CR>

"Tab switching
nnoremap <Leader>tn :tabnew<CR>
nnoremap <Leader>tj :tabnext<CR>
nnoremap <Leader>tk :tabprev<CR>
nnoremap <Leader>tc :tabclose<CR>

" better window movement
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l
nnoremap <C-k> <C-w>k
nnoremap <C-j> <C-w>j

" editing vim
map <Leader>rc :edit $HOME/.vim/vimrc<CR>
map <Leader>dv :edit $HOME/.vim<CR>
map <Leader>rv :source $MYVIMRC<CR>

" saving made eaiser
map <Leader>ww :w!<CR>
map <Leader>wq :wq!<CR>

" quit
map <Leader>qq :q!<CR>

" Quickfix Navigation
nnoremap ]q :cnext<CR>zz
nnoremap [q :cprevious<CR>zz
nnoremap [Q :cfirst<CR>zz
nnoremap ]Q :clast<CR>zz
"}}}
" FZF {{{
let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }

let g:fzf_layout = {
    \ 'down': '~40%'
    \ }

let g:fzf_colors = {
  \ 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'String', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'Search', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }

" If ag is installed, use ag
if executable('ag')
  command! -bang -complete=file GitFiles call fzf#run(fzf#wrap({'source': 'ag --hidden -g ""', 'sink': 'e'}, <bang>0))
  command! -bang -complete=file Files call fzf#run(fzf#wrap({'source': 'ag -u -g ""', 'sink': 'e'}, <bang>0))
else
  command! -bang -complete=file GitFiles call fzf#run(fzf#wrap({'source': 'git ls-files', 'sink': 'e'}, <bang>0))
  command! -bang -complete=file Files call fzf#run(fzf#wrap({'source': 'find .', 'sink': 'e'}, <bang>0))
endif



if has('nvim') && !exists('g:fzf_layout')
  autocmd! FileType fzf
  autocmd  FileType fzf set laststatus=0 noshowmode noruler
    \| autocmd BufLeave <buffer> set laststatus=2 showmode ruler
endif
"}}}
" Custom commands {{{
"Do not respect .gitignore
nnoremap <Leader>F :Files<CR>

"Respect .gitignore
nnoremap <Leader>f :GitFiles<CR>

" Vim based file navigation
nnoremap <Leader>vf :find ./**/*
nnoremap <Leader>vF :find
nnoremap <Leader>e :edit ./
nnoremap <Leader>E :edit<space>

" Insert filename
inoreabbrev %f <C-R>=expand('%:t')<CR>

" Insert file basename
iabbrev %b <C-R>=expand('%:t:r')<CR>

" Insert directory
iabbrev %d <C-R>=expand('%')<CR>

" Insert full path
iabbrev %p <C-R>=expand('%')<CR>

" Treat <li> and <p> tags like the block tags they are
let g:html_indent_tags = 'li\|p'

"File nav
if executable('ag')
  set grepprg=ag\ --vimgrep
  set grepformat=%f:%l:%c%m

  "populate quickfix with \
  command! -nargs=+ -complete=file -bar Ag silent! grep! <args>|cwindow|redraw!
  nnoremap \ :Ag<space>
endif

" bind <Leader>gw to grep word under cursor
nnoremap <Leader>gw :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>

map <Leader>rn :call myfunctions#RenameFile()<cr>

" Create a new file
map <Leader>to :edit <C-R>=expand('%:p:h') . '/'<CR>
map <Leader>td :!mkdir -p <C-R>=expand('%:p:h') . '/'<CR>
"}}}
" Ragtag{{{
" ragtag recommended keybinding
inoremap <M-o> <Esc>o
inoremap <C-j> <Down>

"available globally
let g:ragtag_global_maps = 1
"}}}
" Emmet{{{
" Dont let it override <C-y>
let g:user_emmet_leader_key = '<C-e>'
"}}}
" Ultisnips{{{
let g:UltiSnipsExpandTrigger="<c-k>"
let g:UltiSnipsJumpForwardTrigger="<c-k>"
let g:UltiSnipsJumpBackwardTrigger="<c-j>"
let g:UltiSnipsListSnippets="<c-l>"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"

" Edit snippets
nnoremap <Leader>us :UltiSnipsEdit<CR>
nnoremap <Leader>ue :edit $HOME/.my-snippets<CR>

" Set my snippets
let g:UltiSnipsSnippetDirectories = [$HOME.'/.my-snippets']

" Remove backward jump interference
inoremap <c-x><c-k> <c-x><c-k>
"}}}
" Misc {{{
" Rainbow parentheses
let g:rainbow#max_level = 16
let g:rainbow#pairs = [['(', ')'], ['[', ']'], ['{', '}'], ['<', '>']]

nnoremap <Leader>rp :RainbowParentheses!!<CR>

augroup RainbowParens
  autocmd!
  autocmd Syntax * RainbowParentheses
  autocmd VimEnter * RainbowParentheses
augroup END

" Run ctags on current directory
nnoremap <Leader>gt :call myfunctions#GitCtags()<CR>
"}}}
" ALE{{{
let g:ale_fix_on_save = 0

""Errors
let g:ale_sign_error = '>>'
let g:ale_sign_warning = '--'
let g:ale_set_highlights = 0

"" Linting
let g:ale_lint_on_text_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_enter = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_ignore_lsp = 1

let g:ale_fixers = {
      \ 'ruby': ['standardrb'],
      \ 'javascript': ['prettier_standard'],
      \ 'html': ['prettier_standard']
      \ }

nmap <silent> [a <Plug>(ale_previous_wrap)
nmap <silent> ]a <Plug>(ale_next_wrap)

nnoremap <Leader>ar :ALEFindReferences<CR>
nnoremap <Leader>as :ALESymbolSearch<CR>
nnoremap <Leader>af :ALEFix<CR>
"}}}
" Testing{{{

nmap <silent> t<C-n> :TestNearest<CR>
nmap <silent> t<C-f> :TestFile<CR>
nmap <silent> t<C-s> :TestSuite<CR>
nmap <silent> t<C-l> :TestLast<CR>
nmap <silent> t<C-g> :TestVisit<CR>

let g:test#strategy = "dispatch"

"}}}
"Sign Columns{{{

" Always show the signcolumn, otherwise it would shift the text each time
" diagnostics appear/become resolved.
if has("patch-8.1.1564")
  " Recently vim can merge signcolumn and number column into one
  set signcolumn=number
else
  set signcolumn=yes
endif
"}}}
" Nerdtree{{{
map <C-n> :NERDTreeToggle<CR>
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'
let g:NERDTreeShowHidden = 1
let g:NERDTreeHijackNetrw = 1
let g:NERDTreeMinimalUI = 1
let g:NERDTreeQuitOnOpen = 0
"}}}
" Completion{{{
set cmdheight=2

if has("nvim-0.5")
  " Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
  " delays and poor user experience.
  set updatetime=300

  " Don't pass messages to |ins-completion-menu|.
  set shortmess+=c

  " Set completeopt to have a better completion experience
  set completeopt=menuone,noinsert,noselect

  let g:completion_enable_snippet = 'UltiSnips'

  " Load LSP servers
  :call myfunctions#InstallLanguageServers()

  set omnifunc+=v:lua.vim.lsp.omnifunc
  autocmd BufEnter * lua require'completion'.on_attach()
:lua << END
  require'nvim_lsp'.tsserver.setup{}
  require'nvim_lsp'.solargraph.setup{}
  require'nvim_lsp'.vimls.setup{}
  require'nvim_lsp'.dockerls.setup{}
  require'nvim_lsp'.yamlls.setup{}
  require'nvim_lsp'.bashls.setup{}
  require'nvim_lsp'.elixirls.setup{}
END

  nnoremap <silent> gd            <cmd>lua vim.lsp.buf.declaration()<CR>
  nnoremap <silent> gf            <cmd>lua vim.lsp.buf.definition()<CR>
  nnoremap <silent> K             <cmd>lua vim.lsp.buf.hover()<CR>
  nnoremap <silent> gD            <cmd>lua vim.lsp.buf.implementation()<CR>
  nnoremap <silent> <c-k>         <cmd>lua vim.lsp.buf.signature_help()<CR>
  nnoremap <silent> 1gD           <cmd>lua vim.lsp.buf.type_definition()<CR>
  nnoremap <silent> gr            <cmd>lua vim.lsp.buf.references()<CR>
  nnoremap <silent> <leader>lrn    <cmd>lua vim.lsp.buf.rename()<CR>

  let g:completion_chain_complete_list = {
      \ 'default': [
      \    {'complete_items': ['lsp', 'snippet', 'buffers', 'tabnine' ]},
      \    {'mode': '<c-p>'},
      \    {'mode': '<c-n>'}
      \ ]
  \ }
endif
"}}}

