#!/usr/bin/env sh

##
# @example
#   for a new directory:
#   git-worktree-clone my-project https://
git-worktree-clone () {
  directory="$1"
  url="$2"

  mkdir -p "$directory"
  cd "$directory"
  git clone --bare "$url" ".bare"
  echo "gitdir: ./.bare" > .git

  echo "Your worktree has been created! To start using it do the following:"
  echo "cd $directory"
  echo "git worktree add main"
}
